import { IElement } from '@src/features/email-customizer/type';

export const defaultTemplate = {
  id: 'coming_soon_template',
  name: 'Coming soon template',
  available: true,
  description: 'Template will be released soon. Please feel free to share your feedback.',
  email_type: '',
  elements: [
    {
      id: '69aada25ccdea',
      type: 'column_layout',
      name: 'Two Columns',
      icon: '',
      group: 'general',
      available: true,
      position: 150,
      children: [
        {
          id: '69aada25ccddc',
          type: 'column',
          group: 'hidden',
          available: true,
          children: [
            {
              id: '69aada25ccdce',
              type: 'image',
              name: 'Image',
              icon: '',
              group: 'basic',
              available: true,
              position: 30,
              data: {
                container_group_definition: {
                  component: 'GroupDefinition',
                  title: 'Container settings',
                  description: 'Handle container layout settings',
                },
                padding: {
                  top: 0,
                  right: 10,
                  bottom: 0,
                  left: 0,
                },
                background_color: '#fff',
                image_breaker: {
                  component: 'LineBreaker',
                },
                image_group_definition: {
                  component: 'GroupDefinition',
                  title: 'Image settings',
                  description: 'Handle image settings',
                },
                src: '#',
                align: 'left',
                width: 116,
                url: '#',
                alt: '',
              },
              chosen: false,
              selected: false,
            },
          ],
          data: {
            width: 30,
          },
          icon: '',
        },
        {
          id: '69aada25ccde9',
          type: 'column',
          group: 'hidden',
          available: true,
          children: [
            {
              id: '69aada25ccddd',
              type: 'text',
              name: 'Text',
              icon: '',
              group: 'basic',
              available: true,
              position: 70,
              data: {
                container_group_definition: {
                  component: 'GroupDefinition',
                  title: 'Container settings',
                  description: 'Handle container layout settings',
                },
                padding: {
                  top: 0,
                  right: 0,
                  bottom: 0,
                  left: 0,
                },
                background_color: '#fff',
                border: {
                  side: 'none',
                  width: '1',
                  style: 'solid',
                  color: '#e5e5e5',
                  custom: {
                    top: '1',
                    right: '1',
                    bottom: '1',
                    left: '1',
                  },
                },
                content_breaker: {
                  component: 'LineBreaker',
                },
                content_group_definition: {
                  component: 'GroupDefinition',
                  title: 'Content settings',
                  description: 'Handle content settings',
                },
                font_family: 'Helvetica,Roboto,Arial,sans-serif',
                text_color: '#333439',
                rich_text:
                  '<p style="text-align: right;font-size: 18px;font-weight: 500">My Account      Order Tracking      Contact</p>',
              },
              chosen: false,
              selected: false,
            },
          ],
          data: {
            width: 70,
          },
          icon: '',
        },
      ],
      data: {
        amount_of_columns: 2,
        column_width: 0,
        column_spacing: 0,
        vertical_align: 'top',
        container_setting_breaker: {
          component: 'LineBreaker',
        },
        container_setting_group_definition: {
          component: 'GroupDefinition',
          title: 'Container layout settings',
          description: 'Handle container layout settings',
        },
        padding: {
          top: 20,
          right: 40,
          bottom: 20,
          left: 40,
        },
        border_radius: {
          top_left: 0,
          top_right: 0,
          bottom_left: 0,
          bottom_right: 0,
        },
        background_color: '#ffffff',
        background_image: {
          url: '',
          position: 'default',
          x_position: 0,
          y_position: 0,
          repeat: 'default',
          size: 'default',
        },
        inner_setting_breaker: {
          component: 'LineBreaker',
        },
        inner_setting_group_definition: {
          component: 'GroupDefinition',
          title: 'Inner layout settings',
          description: 'Handle inner layout settings',
        },
        inner_border_radius: {
          top_left: 0,
          top_right: 0,
          bottom_left: 0,
          bottom_right: 0,
        },
        inner_background_color: '#ffffff00',
      },
    },
    {
      id: '69aada25cce2d',
      type: 'text',
      name: 'Text',
      icon: '',
      group: 'basic',
      available: true,
      position: 70,
      data: {
        container_group_definition: {
          component: 'GroupDefinition',
          title: 'Container settings',
          description: 'Handle container layout settings',
        },
        padding: {
          top: 15,
          right: 50,
          bottom: 15,
          left: 50,
        },
        background_color: '#fff',
        border: {
          side: 'none',
          width: '1',
          style: 'solid',
          color: '#e5e5e5',
          custom: {
            top: '1',
            right: '1',
            bottom: '1',
            left: '1',
          },
        },
        content_breaker: {
          component: 'LineBreaker',
        },
        content_group_definition: {
          component: 'GroupDefinition',
          title: 'Content settings',
          description: 'Handle content settings',
        },
        font_family: 'Helvetica,Roboto,Arial,sans-serif',
        text_color: '#333439',
        rich_text:
          "<p>Hi <strong>[yaymail_billing_first_name] [yaymail_billing_last_name],</strong></p>\n<p>Thank you for your order! It's on-hold until we confirm that payment has been received. In the meantime, here's a reminder of what you ordered.</p>",
      },
    },
    {
      id: '69aada25cce47',
      type: 'order_details',
      name: 'Order Details',
      icon: '',
      group: 'woocommerce',
      available: true,
      position: 190,
      data: {
        rich_text: '[yaymail_order_details]',
        payment_instructions: '[yaymail_payment_instructions]',
        container_group_definition: {
          component: 'GroupDefinition',
          title: 'Container settings',
          description: 'Handle container layout settings',
        },
        padding: {
          top: '15',
          right: '50',
          bottom: '15',
          left: '50',
        },
        background_color: '#fff',
        border: {
          side: 'none',
          width: '1',
          style: 'solid',
          color: '#e5e5e5',
          custom: {
            top: '1',
            right: '1',
            bottom: '1',
            left: '1',
          },
        },
        table_setting_breaker: {
          component: 'LineBreaker',
        },
        table_group_definition: {
          component: 'GroupDefinition',
          title: 'Table settings',
          description: 'Handle table settings',
        },
        layout_type: 'modern',
        title: '<p><span style="font-size: 20px"><strong>Order Summary</strong></span></p>',
        title_color: '#1A1A1A',
        text_color: '#636363',
        border_color: '#e5e5e5',
        font_family: 'Helvetica,Roboto,Arial,sans-serif',
        table_content_font_size: '14',
        table_heading_line_breaker: {
          component: 'LineBreaker',
        },
        table_heading_group_definition: {
          component: 'GroupDefinition',
          title: 'Table heading settings',
          description: 'Handle table heading settings',
        },
        table_heading_font_size: '14',
        show_table_header: true,
        product_title: 'Product',
        cost_title: 'Cost',
        quantity_title: 'Quantity',
        price_title: 'Price',
        cart_subtotal_title: 'Subtotal:',
        payment_method_title: 'Payment method:',
        order_total_title: 'Total:',
        order_note_title: 'Note:',
        shipping_title: 'Shipping:',
        discount_title: 'Discount:',
        custom_footer_rows_breaker: {
          component: 'LineBreaker',
        },
        custom_footer_rows_group: {
          component: 'GroupDefinition',
          title: 'Custom Footer Rows',
          description: 'Add custom rows to the order totals footer',
        },
        custom_footer_rows: [],
      },
    },
    {
      id: '69aada25cceeb',
      type: 'column_layout',
      name: 'One Column',
      icon: '',
      group: 'general',
      available: true,
      position: 150,
      children: [
        {
          id: '69aada25cceea',
          type: 'column',
          group: 'hidden',
          available: true,
          children: [
            {
              id: '69aada25cceb9',
              type: 'divider',
              name: 'Divider',
              icon: '',
              group: 'general',
              available: true,
              position: 140,
              data: {
                align: 'center',
                padding: {
                  top: 20,
                  right: 0,
                  bottom: 20,
                  left: 0,
                },
                width: 100,
                height: 2,
                background_color: '#fff',
                divider_color: '#333439',
                divider_type: 'solid',
              },
              chosen: false,
              selected: false,
            },
            {
              id: '69aada25ccec7',
              type: 'text',
              name: 'Text',
              icon: '',
              group: 'basic',
              available: true,
              position: 70,
              data: {
                container_group_definition: {
                  component: 'GroupDefinition',
                  title: 'Container settings',
                  description: 'Handle container layout settings',
                },
                padding: {
                  top: 0,
                  right: 0,
                  bottom: 0,
                  left: 0,
                },
                background_color: '#ffffff00',
                border: {
                  side: 'none',
                  width: '1',
                  style: 'solid',
                  color: '#e5e5e5',
                  custom: {
                    top: '1',
                    right: '1',
                    bottom: '1',
                    left: '1',
                  },
                },
                content_breaker: {
                  component: 'LineBreaker',
                },
                content_group_definition: {
                  component: 'GroupDefinition',
                  title: 'Content settings',
                  description: 'Handle content settings',
                },
                font_family: 'Helvetica,Roboto,Arial,sans-serif',
                text_color: '#333439',
                rich_text:
                  '<p style="text-align: center;margin: 0;font-weight: 300"><span style="font-size: 16px">For questions, contact <u>hello@example.com</u>, visit our <u>FAQs</u>, or <u>chat</u> with us during operating hours for account support</span></p>',
              },
              chosen: false,
              selected: false,
            },
            {
              id: '69aada25cced2',
              type: 'social_icon',
              name: 'Social Icon',
              icon: '',
              group: 'basic',
              available: true,
              position: 90,
              data: {
                container_group_definition: {
                  component: 'GroupDefinition',
                  title: 'Container settings',
                  description: 'Handle container layout settings',
                },
                padding: {
                  top: 20,
                  right: 0,
                  bottom: 20,
                  left: 0,
                },
                background_color: '#fff',
                align: 'center',
                content_breaker: {
                  component: 'LineBreaker',
                },
                content_group_definition: {
                  component: 'GroupDefinition',
                  title: 'Content settings',
                  description: 'Handle content settings',
                },
                width_icon: 24,
                spacing: 24,
                theme: 'SolidDark',
                icon_list: [
                  {
                    icon: 'facebook',
                    url: '#',
                  },
                  {
                    icon: 'instagram',
                    url: '#',
                  },
                  {
                    icon: 'tiktok',
                    url: '#',
                  },
                  {
                    icon: 'youtube',
                    url: '#',
                  },
                ],
              },
              chosen: false,
              selected: false,
            },
            {
              id: '69aada25ccedf',
              type: 'text',
              name: 'Text',
              icon: '',
              group: 'basic',
              available: true,
              position: 70,
              data: {
                container_group_definition: {
                  component: 'GroupDefinition',
                  title: 'Container settings',
                  description: 'Handle container layout settings',
                },
                padding: {
                  top: 0,
                  right: 0,
                  bottom: 20,
                  left: 0,
                },
                background_color: '#fff',
                border: {
                  side: 'none',
                  width: '1',
                  style: 'solid',
                  color: '#e5e5e5',
                  custom: {
                    top: '1',
                    right: '1',
                    bottom: '1',
                    left: '1',
                  },
                },
                content_breaker: {
                  component: 'LineBreaker',
                },
                content_group_definition: {
                  component: 'GroupDefinition',
                  title: 'Content settings',
                  description: 'Handle content settings',
                },
                font_family: 'Helvetica,Roboto,Arial,sans-serif',
                text_color: '#77859B',
                rich_text:
                  '<p style="text-align: center;margin: 0;font-weight: 300"><span style="font-size: 12px">© 2025 YayCommerce.com</span></p>',
              },
              chosen: false,
              selected: false,
            },
          ],
          data: {
            width: 100,
          },
          icon: '',
        },
      ],
      data: {
        amount_of_columns: 1,
        column_width: 0,
        column_spacing: 0,
        vertical_align: 'top',
        container_setting_breaker: {
          component: 'LineBreaker',
        },
        container_setting_group_definition: {
          component: 'GroupDefinition',
          title: 'Container layout settings',
          description: 'Handle container layout settings',
        },
        padding: {
          top: 10,
          bottom: 10,
          left: 40,
          right: 40,
        },
        border_radius: {
          top_left: 0,
          top_right: 0,
          bottom_left: 0,
          bottom_right: 0,
        },
        background_color: '#fff',
        background_image: {
          url: '',
          position: 'default',
          x_position: 0,
          y_position: 0,
          repeat: 'default',
          size: 'default',
        },
        inner_setting_breaker: {
          component: 'LineBreaker',
        },
        inner_setting_group_definition: {
          component: 'GroupDefinition',
          title: 'Inner layout settings',
          description: 'Handle inner layout settings',
        },
        inner_border_radius: {
          top_left: 0,
          top_right: 0,
          bottom_left: 0,
          bottom_right: 0,
        },
        inner_background_color: '#ffffff00',
      },
    },
  ] as unknown as IElement[],
};
