<?php
/**
 * Plugin adapter for Email Builder.
 * Generated by yaycommerce-init. Edit values as needed.
 */

defined( 'ABSPATH' ) || exit;

class EmailBuilderPluginAdapter implements \EmailBuilderScoped\YayCommerce\AdminShell\Contracts\PluginMenuAdapter, \EmailBuilderScoped\YayCommerce\AdminShell\Contracts\AddonHostAdapter {
    public function get_menu_title(): string {
        return 'Email Builder'; }
    public function get_page_title(): string {
        return 'Email Builder'; }
    public function get_menu_slug(): string {
        return 'email-builder-settings'; }
    public function get_settings_page_callback(): ?callable {
        return static function (): void {
            include_once EMAIL_BUILDER_PLUGIN_PATH . 'templates/pages/settings.php';
        }; } // Set your render callback here
    public function get_settings_page_position(): ?int {
        return 160; }
    public function get_capability(): string {
        return 'manage_options'; }
    public function get_plugin_basename(): string {
        return EMAIL_BUILDER_PLUGIN_BASENAME; }
    public function get_settings_label(): string {
        return 'Start Customizing'; }
    public function get_docs_url(): string {
        return 'https://docs.yaycommerce.com/email-builder/'; }
    public function get_pro_url(): string {
        return 'https://yaycommerce.com/email-builder/'; }

    // --- Addon host ---
    public function get_addon_licensing_filter(): string {
        return 'email_builder_available_licensing_plugins'; }
}
